apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: django-app
  namespace: argocd
spec:
  destination:
    namespace: aplication-django
    server: "https://kubernetes.default.svc"
  project: app-django
  source:
    path: .
    repoURL: git@github.com:alexsandroocanha/Django-DevOps-Pipeline-Manifest.git
    targetRevision: HEAD
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutSyncOnly=true